Add F# types extensions
codehardth/Codehard.Functional pull request #10
Opened 2022-10-14 21:15 UTC by rungwiroon

2022-11-21 04:40 UTC, Desz01ate requested changes

2022-11-21 04:40 UTC, Desz01ate commented on Codehard.Functional.FSharp/Prelude.cs
> +namespace Codehard.Functional.FSharp
ใช้ top level namespace ดีกว่าครับ จะได้ convention เหมือนกันกับโค้ดก่อนหน้า

2022-11-21 04:40 UTC, Desz01ate commented on Codehard.Functional.FSharp/ResultExtensions.cs
> +        /// Conver F# Result to Fin
typo ครับ

2022-11-28 08:01 UTC, Desz01ate commented
LGTM!

2022-11-28 08:01 UTC, Desz01ate approved these changes
LGTM!

2022-11-28 08:09 UTC, gfhdlcod02 approved these changes

2022-11-28 08:10 UTC, merged