Combine Aff<A> withConsumeContext
codehardth/Codehard.Functional pull request #8
Opened 2022-10-13 20:48 UTC by rungwiroon

2022-10-15 08:01 UTC, Desz01ate requested changes

2022-10-15 08:01 UTC, Desz01ate commented on Codehard.Functional.MassTransit/AsyncEffectExtensions.cs
> +public struct AffWithConsumeContext<TRes>
แยกออกมาเป็นอีกไฟล์ดีกว่าหรือเปล่าครับ

2022-10-15 17:13 UTC, rungwiroon commented on Codehard.Functional.MassTransit/AsyncEffectExtensions.cs
> +        var @this = this;
เนื่องจากว่าจะมีการเรียกใช้ `this.consumeContext` จากใน Lambda Expression ทำให้ต้องมีการ copy มาใน local variable ก่อนครับ

2022-10-15 17:14 UTC, rungwiroon commented on Codehard.Functional.MassTransit/AsyncEffectExtensions.cs
> +        var @this = this;
![image](https://user-images.githubusercontent.com/356565/195999352-32bc6635-e591-46e3-850b-da1636bea7e3.png)

2022-10-15 17:35 UTC, rungwiroon commented on Codehard.Functional.MassTransit/AsyncEffectExtensions.cs
> +public struct AffWithConsumeContext<TRes>
แยกล่ะครับ

2022-10-26 08:29 UTC, Desz01ate approved these changes
lgtm!

2022-10-27 02:54 UTC, gfhdlcod02 approved these changes

2022-10-27 03:16 UTC, merged