Add With and Guard extension to Aff
codehardth/Codehard.Functional pull request #9
Opened 2022-10-14 18:15 UTC by rungwiroon

2022-10-26 09:15 UTC, Desz01ate requested changes

2022-10-26 09:15 UTC, Desz01ate commented on Codehard.Functional.Tests/AffWithExtTests.cs
> +            // Arrage
Typo ครับ

2022-10-26 09:15 UTC, Desz01ate commented on Codehard.Functional/AffWithCompensation.cs
> +
empty lines ครับ

2022-10-26 09:15 UTC, Desz01ate commented on Codehard.Functional.Tests/Codehard.Functional.Tests.csproj
> +    <IsPackable>false</IsPackable>
ไม่น่าจำเป็นนะครับ

2022-10-26 09:15 UTC, Desz01ate commented on Codehard.Functional/Prelude.cs
> +﻿namespace Codehard.Functional
ใช้ file scoped namespace ดีกว่าครับ จะได้ consistent กับโค้ดที่เหลือ

2022-10-26 09:21 UTC, Desz01ate requested changes
don't mind this comment, it was a mistake.

2022-10-26 09:22 UTC, Desz01ate approved these changes
lgtm!

2022-10-27 16:27 UTC, gfhdlcod02 approved these changes

2022-10-27 16:36 UTC, merged